
[package]
name    = "gli-rs"
version = "0.2.0"
authors = ["usami-renko <usami-ssc@protonmail.com>"]
edition = "2018"
build   = "build.rs"

homepage    = "https://github.com/Usami-Renko/gli-rs"
repository  = "https://github.com/Usami-Renko/gli-rs"
description = "Rust binding for OpenGL Image(GLI)"
keywords    = ["Graphics", "gli", "Texture"]
license     = "MIT"

include = [
    "src/*",
    "build/bindings.rs",
    "build.rs",
    "Cargo.toml",
    "vendors/gli/external/*",
    "vendors/gli/gli/*",
    "wrapper/*",
]

[badges]
travis-ci = { repository = "Usami-Renko/gli-rs" }

[dependencies]
failure = "0.1.5"

[build-dependencies]
cc = { version = "1.0.30", features = ["parallel"] }

[build-dependencies.bindgen]
version = "0.48.0"
optional = true

[features]
bindings = ["bindgen"] # use this feature to enable binding generation.

[profile.release]
opt-level = 3
lto = true
